# Base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set the permissions for the shared folder
RUN chmod -R 777 ./shared

# Expose the desired port (change it to the appropriate port used by your application)
EXPOSE 3001

# Run the application
CMD ["npm", "start"]